In [ ]:
# individuare a livello di test dei clienti che hanno piu macchine e con lavorazione costante nel tempo

# CMS A.R.S TECH 20 - 24316
# WREN KITCHENS LIMITED 6 - K4724
# TRENDWOOD INCORPORATED 10 - I9300
# TINO SANA S.R.L. 7 - 50176

#Party_Name	Model	Invent_Serial_Cod	sdhMachineId	Count of sdhMachineId
#A.R.S. TECH SRL	CARES3	CMSBK61	1288d083-60ca-43bf-93f4-5a508cb1a32b	1
#A.R.S. TECH SRL	SPROLINE	CMSBF28	1fb823dc-dd9c-466f-ad14-15b2e56d7a60	1
#A.R.S. TECH SRL	CETHOS	CMSBI56	423324cd-c222-476a-9c98-70cbfec0cb37	1
#A.R.S. TECH SRL	TIME100	AA10005421	486f5c4d-fbde-4327-919d-0d91d3de2f80	1
#A.R.S. TECH SRL	CMAXIMA	CMSBJ58	634c4761-aeb7-425b-aa5d-943828e6db86	1
#A.R.S. TECH SRL	CANTARES	CMS9454	6a03dc3b-e9b7-4a6c-9503-abc4303ec677	1
#A.R.S. TECH SRL	CARES2	CMSB669	7f6adef2-9526-47cb-934e-fc41679876c5	1
#A.R.S. TECH SRL	CARES3	CMSBN05	87171643-315b-42da-aeff-c5c55f2fb001	1
#A.R.S. TECH SRL	CMAXIMA	CMSBK60	92263343-f84e-49aa-a29a-e93a903bed49	1
#A.R.S. TECH SRL	CANTARES	CMSBJ56	9372135d-aa2b-4844-b225-65739968793b	1
#A.R.S. TECH SRL	CPOSEIDON	CMS7495	94bdc30b-7a57-44b6-86ce-bec800193342	1
#A.R.S. TECH SRL	CANTARES	CMSB667	a8153a02-54e0-4160-963d-14f62a0be05c	1
#A.R.S. TECH SRL	CMAXIMA	CMSBI55	c2350446-1efb-4da4-a4cf-16090800d0c1	1
#A.R.S. TECH SRL	CANTARES	CMSBN10	ca18c6b7-04d0-4f45-a9ed-f2779c93d89c	1
#A.R.S. TECH SRL	CANTARES	CMSBN12	d0c9e3c2-5c46-423f-9ae4-123d950b578c	1
#A.R.S. TECH SRL	CANTARES	CMS9449	d233a97b-d602-4506-920a-9c1e697fe624	1
#A.R.S. TECH SRL	CPOSEIDON	CMS8752	d46e1c92-d7ad-4a2a-a055-cba5807ac95e	1
#A.R.S. TECH SRL	CARES2	CMSB668	e0b772f8-60aa-43e3-a85f-d757ed632c2b	1
#A.R.S. TECH SRL	CMAXIMA	CMS9451	f7de5ea8-032b-44b3-82c6-6837916d6dce	1
#A.R.S. TECH SRL	CARES2	CMS8739	fe789858-a70d-44e4-8a6c-352b62e2e28b	1
#TINO SANA S.R.L.	FLEXSTORE HP	ACL/364/01	0f6f5343-73a0-4b01-8d9b-e5b09377407f	1
#TINO SANA S.R.L.	GABBIANI G2115	ACL/364/04	23d45538-de4d-4bdf-a461-235e44a2233f	1
#TINO SANA S.R.L.	M200	AA10007086	342f98d8-596e-4052-a222-717b683eb82d	1
#TINO SANA S.R.L.	CX210	AB00029092	4faf21e4-10f3-46ba-81a5-e1fdb092e3de	1
#TINO SANA S.R.L.	STEFANI KD HP	AH00006599	7bfe93cf-1cee-40e0-87ad-9b12629480d2	1
#TINO SANA S.R.L.	X200 CELL	ACL/364/02	ad47a0b7-7c41-4460-af2a-9f32ae94330e	1
#TINO SANA S.R.L.	X200 CELL	ACL/364/03	b5090d76-7694-47c3-8c18-59d1d63726f4	1
#TRENDWOOD INCORPORATED	ACCORD 40 FX	AA10003796	21757d00-9cc8-4e1e-bce3-508f0709eb47	1
#TRENDWOOD INCORPORATED	ACCORD 40 FX	AA10003801	341acb8d-045f-4a41-9264-016bd740cfce	1
#TRENDWOOD INCORPORATED	ACCORD 40 FX	AA10003798	5089abe1-8b55-40dd-913b-42e1fbc92459	1
#TRENDWOOD INCORPORATED	ACCORD 40 FX	AA10003802	6b33fc4e-65a6-47d9-9c9e-3f856b437c39	1
#TRENDWOOD INCORPORATED	ACCORD 40 FX	AA10003803	93ca7086-f53f-4f90-bb49-9bfb7d5994c9	1
#TRENDWOOD INCORPORATED	ACCORD 40 FX	AA10003795	aa73c60c-2ab4-4441-9683-f48197a36686	1
#TRENDWOOD INCORPORATED	ACCORD 40 FX	AA10003800	ae1396c8-01d8-429a-b488-f1277db72375	1
#TRENDWOOD INCORPORATED	ACCORD 40 FX	AA10003797	c91f1766-3fd6-40e9-876d-e949f266bed3	1
#TRENDWOOD INCORPORATED	ACCORD 40 FX	AA10003804	df23fa2a-6d9a-4d98-9257-97f15fc8f6c9	1
#TRENDWOOD INCORPORATED	ACCORD 40 FX	AA10003799	ebe43721-670d-4f19-b5ea-35214843b7dc	1
#WREN KITCHENS LIMITED	GABBIANIGT3130	ACL/353/01	0e9302aa-21f2-4cdd-bf47-60b39297afa7	1
#WREN KITCHENS LIMITED	STEFANI KDR	AH00004844	18dae90c-6cbc-476c-9802-0ae0ff256fe0	1
#WREN KITCHENS LIMITED	STEFANI SB	ACL/354/02	51b62039-dbd4-45c6-8492-9dc57e6cde3d	1
#WREN KITCHENS LIMITED	STEFANI ONE	ACL/357/03	99e9dead-5156-4623-b489-537d80f0e3de	1
#WREN KITCHENS LIMITED	STEFANI ONE	ACL/355/01	a489a489-7eb0-4dd7-ad40-dfd5bb890e6c	1
#WREN KITCHENS LIMITED	STEFANI 60	ACL/353/03	ff128e80-1db7-4569-b255-6377a3d3962a	1

In [ ]:
######################################
#AGGIORNAMENTO DEL DATASET PRINCIPALE - IMPORTO I DATI DEGLI STATI MACCHINA
#####################################
# %%
import pandas as pd
import pyodbc
import warnings
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')

cnxn = pyodbc.connect(r'Driver=SQL Server;Server=dwhbisqltst;Database=SCM_UTE_02;Trusted_Connection=yes;')
cursor = cnxn.cursor()

sql_query1 = """
WITH Data AS (
    SELECT 
        sdhMachineId, 
        data_value, 
        CONVERT(datetime, [timestamp]) AS [from]
    FROM [SCM_INTEGRATION].[dbo].[INT_CR_Measure_hot_MachineStatus]
    WHERE [timestamp_date] > DATEADD(DAY, -210, GETDATE())
	and sdhMachineId IN (
    '0e9302aa-21f2-4cdd-bf47-60b39297afa7',
    '0f6f5343-73a0-4b01-8d9b-e5b09377407f',
    '1288d083-60ca-43bf-93f4-5a508cb1a32b',
    '18dae90c-6cbc-476c-9802-0ae0ff256fe0',
    '1fb823dc-dd9c-466f-ad14-15b2e56d7a60',
    '21757d00-9cc8-4e1e-bce3-508f0709eb47',
    '23d45538-de4d-4bdf-a461-235e44a2233f',
    '341acb8d-045f-4a41-9264-016bd740cfce',
    '342f98d8-596e-4052-a222-717b683eb82d',
    '423324cd-c222-476a-9c98-70cbfec0cb37',
    '486f5c4d-fbde-4327-919d-0d91d3de2f80',
    '4faf21e4-10f3-46ba-81a5-e1fdb092e3de',
    '5089abe1-8b55-40dd-913b-42e1fbc92459',
    '51b62039-dbd4-45c6-8492-9dc57e6cde3d',
    '634c4761-aeb7-425b-aa5d-943828e6db86',
    '6a03dc3b-e9b7-4a6c-9503-abc4303ec677',
    '6b33fc4e-65a6-47d9-9c9e-3f856b437c39',
    '7bfe93cf-1cee-40e0-87ad-9b12629480d2',
    '7f6adef2-9526-47cb-934e-fc41679876c5',
    '87171643-315b-42da-aeff-c5c55f2fb001',
    '92263343-f84e-49aa-a29a-e93a903bed49',
    '9372135d-aa2b-4844-b225-65739968793b',
    '93ca7086-f53f-4f90-bb49-9bfb7d5994c9',
    '94bdc30b-7a57-44b6-86ce-bec800193342',
    '99e9dead-5156-4623-b489-537d80f0e3de',
    'a489a489-7eb0-4dd7-ad40-dfd5bb890e6c',
    'a8153a02-54e0-4160-963d-14f62a0be05c',
    'aa73c60c-2ab4-4441-9683-f48197a36686',
    'ad47a0b7-7c41-4460-af2a-9f32ae94330e',
    'ae1396c8-01d8-429a-b488-f1277db72375',
    'b5090d76-7694-47c3-8c18-59d1d63726f4',
    'c2350446-1efb-4da4-a4cf-16090800d0c1',
    'c91f1766-3fd6-40e9-876d-e949f266bed3',
    'ca18c6b7-04d0-4f45-a9ed-f2779c93d89c',
    'd0c9e3c2-5c46-423f-9ae4-123d950b578c',
    'd233a97b-d602-4506-920a-9c1e697fe624',
    'd46e1c92-d7ad-4a2a-a055-cba5807ac95e',
    'df23fa2a-6d9a-4d98-9257-97f15fc8f6c9',
    'e0b772f8-60aa-43e3-a85f-d757ed632c2b',
    'ebe43721-670d-4f19-b5ea-35214843b7dc',
    'f7de5ea8-032b-44b3-82c6-6837916d6dce',
    'fe789858-a70d-44e4-8a6c-352b62e2e28b',
    'ff128e80-1db7-4569-b255-6377a3d3962a'
)
      AND [timestamp_date] <= GETDATE()
),
MinMaxDates AS (
    SELECT 
        MIN([from]) AS min_from,
        MAX([from]) AS max_from
    FROM Data
),
InitialRow AS (
    SELECT 
        DISTINCT sdhMachineId, 
        'UPDATED' AS data_value, 
        (SELECT min_from FROM MinMaxDates) AS [from]
    FROM Data
),
FinalRow AS (
    SELECT 
        DISTINCT sdhMachineId, 
        'UPDATED' AS data_value, 
        (SELECT max_from FROM MinMaxDates) AS [from]
    FROM Data
),
AllData AS (
    SELECT 
        sdhMachineId, 
        data_value, 
        [from]
    FROM Data
    UNION ALL
    SELECT 
        sdhMachineId, 
        data_value, 
        [from]
    FROM InitialRow
    UNION ALL
    SELECT 
        sdhMachineId, 
        data_value, 
        [from]
    FROM FinalRow
),
AllDataWithLag AS (
    SELECT 
        sdhMachineId, 
        data_value, 
        [from],
        LAG([from]) OVER (PARTITION BY sdhMachineId ORDER BY [from] DESC) AS [to]
    FROM AllData
),
DateSplit AS (
    SELECT
        sdhMachineId,
        data_value,
        [from],
        [to],
        CAST([from] AS DATE) AS start_date,
        CAST([to] AS DATE) AS end_date
    FROM AllDataWithLag
),
DateRange AS (
    SELECT
        sdhMachineId,
        data_value,
        [from],
        [to],
        start_date,
        end_date,
        start_date AS current_day
    FROM DateSplit
    UNION ALL
    SELECT
        sdhMachineId,
        data_value,
        [from],
        [to],
        start_date,
        end_date,
        DATEADD(DAY, 1, current_day) AS current_day
    FROM DateRange
    WHERE DATEADD(DAY, 1, current_day) <= end_date
)
SELECT
    sdhMachineId,
    data_value,
    CASE 
        WHEN current_day = start_date THEN [from]
        ELSE CAST(current_day AS DATETIME)
    END AS [from],
    CASE 
        WHEN current_day = end_date THEN [to]
        ELSE DATEADD(SECOND, -1, DATEADD(DAY, 1, CAST(current_day AS DATETIME)))
    END AS [to]
FROM DateRange
WHERE sdhMachineId IN (
    '0e9302aa-21f2-4cdd-bf47-60b39297afa7',
    '0f6f5343-73a0-4b01-8d9b-e5b09377407f',
    '1288d083-60ca-43bf-93f4-5a508cb1a32b',
    '18dae90c-6cbc-476c-9802-0ae0ff256fe0',
    '1fb823dc-dd9c-466f-ad14-15b2e56d7a60',
    '21757d00-9cc8-4e1e-bce3-508f0709eb47',
    '23d45538-de4d-4bdf-a461-235e44a2233f',
    '341acb8d-045f-4a41-9264-016bd740cfce',
    '342f98d8-596e-4052-a222-717b683eb82d',
    '423324cd-c222-476a-9c98-70cbfec0cb37',
    '486f5c4d-fbde-4327-919d-0d91d3de2f80',
    '4faf21e4-10f3-46ba-81a5-e1fdb092e3de',
    '5089abe1-8b55-40dd-913b-42e1fbc92459',
    '51b62039-dbd4-45c6-8492-9dc57e6cde3d',
    '634c4761-aeb7-425b-aa5d-943828e6db86',
    '6a03dc3b-e9b7-4a6c-9503-abc4303ec677',
    '6b33fc4e-65a6-47d9-9c9e-3f856b437c39',
    '7bfe93cf-1cee-40e0-87ad-9b12629480d2',
    '7f6adef2-9526-47cb-934e-fc41679876c5',
    '87171643-315b-42da-aeff-c5c55f2fb001',
    '92263343-f84e-49aa-a29a-e93a903bed49',
    '9372135d-aa2b-4844-b225-65739968793b',
    '93ca7086-f53f-4f90-bb49-9bfb7d5994c9',
    '94bdc30b-7a57-44b6-86ce-bec800193342',
    '99e9dead-5156-4623-b489-537d80f0e3de',
    'a489a489-7eb0-4dd7-ad40-dfd5bb890e6c',
    'a8153a02-54e0-4160-963d-14f62a0be05c',
    'aa73c60c-2ab4-4441-9683-f48197a36686',
    'ad47a0b7-7c41-4460-af2a-9f32ae94330e',
    'ae1396c8-01d8-429a-b488-f1277db72375',
    'b5090d76-7694-47c3-8c18-59d1d63726f4',
    'c2350446-1efb-4da4-a4cf-16090800d0c1',
    'c91f1766-3fd6-40e9-876d-e949f266bed3',
    'ca18c6b7-04d0-4f45-a9ed-f2779c93d89c',
    'd0c9e3c2-5c46-423f-9ae4-123d950b578c',
    'd233a97b-d602-4506-920a-9c1e697fe624',
    'd46e1c92-d7ad-4a2a-a055-cba5807ac95e',
    'df23fa2a-6d9a-4d98-9257-97f15fc8f6c9',
    'e0b772f8-60aa-43e3-a85f-d757ed632c2b',
    'ebe43721-670d-4f19-b5ea-35214843b7dc',
    'f7de5ea8-032b-44b3-82c6-6837916d6dce',
    'fe789858-a70d-44e4-8a6c-352b62e2e28b',
    'ff128e80-1db7-4569-b255-6377a3d3962a'
)
ORDER BY sdhMachineId, [from]
OPTION (MAXRECURSION 1000);

"""

df_status = pd.read_sql(sql_query1, cnxn)

In [ ]:
print(df_status.to_string(max_cols=df_status.shape[1]))

In [ ]:
import pandas as pd
import os

file_path = r'C:\Users\dgarattoni\OneDrive - scmgroup.com\my ONEDRIVE\Business Analyst in Spare Parts\06.CONTROL ROOM\8. REPORTISTICA\status data\df_Status_.csv'


df_status.to_csv(file_path, index=False)

print(f"DataFrame saved to {file_path}")

In [ ]:
######################################
#AGGIORNAMENTO DEL DATASET PRINCIPALE - IMPORTO I DATI FREDDI
#####################################
# %%
import pandas as pd
import pyodbc
import warnings
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')

cnxn1 = pyodbc.connect(r'Driver=SQL Server;Server=dwhbisqltst;Database=SCM_UTE_02;Trusted_Connection=yes;')
cursor1 = cnxn1.cursor()

sql_query1 = """
DROP TABLE IF EXISTS #TempTable; 
WITH ColdData AS (
    SELECT 
        [type], [key], [sdhMachineId], MAX([timestamp]) AS max_timestamp, 
        [properties_group], [properties_name], [properties_type], [properties_location] ,[properties_model]
    FROM 
        [SCM_INTEGRATION].[dbo].[INT_CR_Measure_cold] 
    WHERE 1=1
     and properties_type not in ('LUBRO')
     and sdhMachineId IN (
    '0e9302aa-21f2-4cdd-bf47-60b39297afa7',
    '0f6f5343-73a0-4b01-8d9b-e5b09377407f',
    '1288d083-60ca-43bf-93f4-5a508cb1a32b',
    '18dae90c-6cbc-476c-9802-0ae0ff256fe0',
    '1fb823dc-dd9c-466f-ad14-15b2e56d7a60',
    '21757d00-9cc8-4e1e-bce3-508f0709eb47',
    '23d45538-de4d-4bdf-a461-235e44a2233f',
    '341acb8d-045f-4a41-9264-016bd740cfce',
    '342f98d8-596e-4052-a222-717b683eb82d',
    '423324cd-c222-476a-9c98-70cbfec0cb37',
    '486f5c4d-fbde-4327-919d-0d91d3de2f80',
    '4faf21e4-10f3-46ba-81a5-e1fdb092e3de',
    '5089abe1-8b55-40dd-913b-42e1fbc92459',
    '51b62039-dbd4-45c6-8492-9dc57e6cde3d',
    '634c4761-aeb7-425b-aa5d-943828e6db86',
    '6a03dc3b-e9b7-4a6c-9503-abc4303ec677',
    '6b33fc4e-65a6-47d9-9c9e-3f856b437c39',
    '7bfe93cf-1cee-40e0-87ad-9b12629480d2',
    '7f6adef2-9526-47cb-934e-fc41679876c5',
    '87171643-315b-42da-aeff-c5c55f2fb001',
    '92263343-f84e-49aa-a29a-e93a903bed49',
    '9372135d-aa2b-4844-b225-65739968793b',
    '93ca7086-f53f-4f90-bb49-9bfb7d5994c9',
    '94bdc30b-7a57-44b6-86ce-bec800193342',
    '99e9dead-5156-4623-b489-537d80f0e3de',
    'a489a489-7eb0-4dd7-ad40-dfd5bb890e6c',
    'a8153a02-54e0-4160-963d-14f62a0be05c',
    'aa73c60c-2ab4-4441-9683-f48197a36686',
    'ad47a0b7-7c41-4460-af2a-9f32ae94330e',
    'ae1396c8-01d8-429a-b488-f1277db72375',
    'b5090d76-7694-47c3-8c18-59d1d63726f4',
    'c2350446-1efb-4da4-a4cf-16090800d0c1',
    'c91f1766-3fd6-40e9-876d-e949f266bed3',
    'ca18c6b7-04d0-4f45-a9ed-f2779c93d89c',
    'd0c9e3c2-5c46-423f-9ae4-123d950b578c',
    'd233a97b-d602-4506-920a-9c1e697fe624',
    'd46e1c92-d7ad-4a2a-a055-cba5807ac95e',
    'df23fa2a-6d9a-4d98-9257-97f15fc8f6c9',
    'e0b772f8-60aa-43e3-a85f-d757ed632c2b',
    'ebe43721-670d-4f19-b5ea-35214843b7dc',
    'f7de5ea8-032b-44b3-82c6-6837916d6dce',
    'fe789858-a70d-44e4-8a6c-352b62e2e28b',
    'ff128e80-1db7-4569-b255-6377a3d3962a'
)
    
    GROUP BY 
        [type], [key], [sdhMachineId], [properties_group], [properties_name], [properties_type], [properties_location],[properties_model]
), 
OrderedData AS (
    SELECT 
        hot.[key], 
        cold.[properties_type], 
        cold.[properties_location], 
        cold.[properties_model],
        hot.[correlationKey], 
        hot.[type], 
        hot.[sdhMachineId], 
        hot.data_value, 
        hot.[timestamp] AS [from], 
        LAG(hot.[timestamp]) OVER (
            PARTITION BY hot.sdhMachineId, cold.properties_type, cold.properties_location ,cold.properties_model
            ORDER BY hot.[timestamp] DESC
        ) AS prev_from 
    FROM (
        SELECT * FROM scm_integration.dbo.INT_CR_Measure_hot_MachineAuxiliaryGroupsStatus
        UNION ALL
        SELECT * FROM scm_integration.dbo.INT_CR_Measure_hot_MachineOperatingGroupsStatus
    ) AS hot 
    INNER JOIN 
        ColdData AS cold 
        ON hot.sdhMachineId = cold.sdhMachineId 
        AND hot.correlationKey = cold.[key]
    WHERE 
        CAST(hot.[timestamp_date] AS datetime) > DATEADD(DAY, -210, GETDATE())
        
        AND hot.sdhMachineId IN (
    '0e9302aa-21f2-4cdd-bf47-60b39297afa7',
    '0f6f5343-73a0-4b01-8d9b-e5b09377407f',
    '1288d083-60ca-43bf-93f4-5a508cb1a32b',
    '18dae90c-6cbc-476c-9802-0ae0ff256fe0',
    '1fb823dc-dd9c-466f-ad14-15b2e56d7a60',
    '21757d00-9cc8-4e1e-bce3-508f0709eb47',
    '23d45538-de4d-4bdf-a461-235e44a2233f',
    '341acb8d-045f-4a41-9264-016bd740cfce',
    '342f98d8-596e-4052-a222-717b683eb82d',
    '423324cd-c222-476a-9c98-70cbfec0cb37',
    '486f5c4d-fbde-4327-919d-0d91d3de2f80',
    '4faf21e4-10f3-46ba-81a5-e1fdb092e3de',
    '5089abe1-8b55-40dd-913b-42e1fbc92459',
    '51b62039-dbd4-45c6-8492-9dc57e6cde3d',
    '634c4761-aeb7-425b-aa5d-943828e6db86',
    '6a03dc3b-e9b7-4a6c-9503-abc4303ec677',
    '6b33fc4e-65a6-47d9-9c9e-3f856b437c39',
    '7bfe93cf-1cee-40e0-87ad-9b12629480d2',
    '7f6adef2-9526-47cb-934e-fc41679876c5',
    '87171643-315b-42da-aeff-c5c55f2fb001',
    '92263343-f84e-49aa-a29a-e93a903bed49',
    '9372135d-aa2b-4844-b225-65739968793b',
    '93ca7086-f53f-4f90-bb49-9bfb7d5994c9',
    '94bdc30b-7a57-44b6-86ce-bec800193342',
    '99e9dead-5156-4623-b489-537d80f0e3de',
    'a489a489-7eb0-4dd7-ad40-dfd5bb890e6c',
    'a8153a02-54e0-4160-963d-14f62a0be05c',
    'aa73c60c-2ab4-4441-9683-f48197a36686',
    'ad47a0b7-7c41-4460-af2a-9f32ae94330e',
    'ae1396c8-01d8-429a-b488-f1277db72375',
    'b5090d76-7694-47c3-8c18-59d1d63726f4',
    'c2350446-1efb-4da4-a4cf-16090800d0c1',
    'c91f1766-3fd6-40e9-876d-e949f266bed3',
    'ca18c6b7-04d0-4f45-a9ed-f2779c93d89c',
    'd0c9e3c2-5c46-423f-9ae4-123d950b578c',
    'd233a97b-d602-4506-920a-9c1e697fe624',
    'd46e1c92-d7ad-4a2a-a055-cba5807ac95e',
    'df23fa2a-6d9a-4d98-9257-97f15fc8f6c9',
    'e0b772f8-60aa-43e3-a85f-d757ed632c2b',
    'ebe43721-670d-4f19-b5ea-35214843b7dc',
    'f7de5ea8-032b-44b3-82c6-6837916d6dce',
    'fe789858-a70d-44e4-8a6c-352b62e2e28b',
    'ff128e80-1db7-4569-b255-6377a3d3962a'
)) 
SELECT 
    * 
INTO 
    #TempTable 
FROM 
    OrderedData; 

DROP TABLE IF EXISTS #TempTable_Dates; 
WITH MinMaxDates AS (
    SELECT 
        MIN(CONVERT(DATE, [from])) AS MinDate, 
        MAX(CONVERT(DATE, prev_from)) AS MaxDate 
    FROM 
        #TempTable
) 
SELECT 
    DISTINCT Date 
INTO 
    #TempTable_Dates 
FROM 
    MinMaxDates 
CROSS APPLY (
    SELECT 
        DATEADD(DAY, number, MinDate) AS Date 
    FROM 
        master..spt_values 
    WHERE 
        type = 'P' 
        AND DATEADD(DAY, number, MinDate) <= MaxDate
) AS Dates;
"""
cursor1.execute(sql_query1)
cnxn1.commit()


sql_query2 = """
SELECT 
    t.[key], t.properties_type, t.properties_location,t.properties_model, t.correlationKey, t.[type], t.sdhMachineId, t.data_value, 
    d.Date, 
    CASE 
        WHEN CONVERT(DATE, t.[from]) = d.Date THEN t.[from] 
        ELSE CONVERT(DATETIMEOFFSET, CONVERT(VARCHAR(10), d.Date) + 'T00:00:00+00:00') 
    END AS from_datetime, 
    CASE 
        WHEN CONVERT(DATE, t.[prev_from]) = d.Date THEN t.[prev_from] 
        ELSE CONVERT(DATETIMEOFFSET, CONVERT(VARCHAR(10), d.Date) + 'T23:59:59+00:00') 
    END AS to_datetime 
FROM 
    #TempTable AS t 
LEFT JOIN 
    #TempTable_Dates AS d 
    ON d.Date >= CONVERT(DATE, t.[from]) 
    AND d.Date <= CONVERT(DATE, t.prev_from) 
GROUP BY 
    t.[key], t.properties_type, t.properties_location,properties_model, t.correlationKey, t.[type], t.sdhMachineId, t.data_value, 
    d.Date, t.[from], t.prev_from 
ORDER BY 
    t.correlationKey, from_datetime DESC;
"""

df_status_op = pd.read_sql(sql_query2, cnxn1)
print(df_status_op.to_string(max_cols=df_status_op.shape[1]))


cursor1.close()
cnxn1.close()

In [1]:
import pandas as pd

# Define the file path
file_path1 = r'C:\Users\dgarattoni\OneDrive - scmgroup.com\my ONEDRIVE\Business Analyst in Spare Parts\06.CONTROL ROOM\8. REPORTISTICA\status data\df_Status_op_.csv'

# Assuming df_status_op is already defined
df_status_op.to_csv(file_path1, index=False)

print(f"DataFrame saved to {file_path1}")

NameError: name 'df_status_op' is not defined

In [ ]:
### abbiamo bisogno di dire cosa succede sulla macchina al momento di un determinato status
# tipo prendendo la matricola AA10003795 vediamo gli stati macchina e cosa succede nel frattempo:
# tipo la macchina è stata in exe il 23/07/2024 19:09:40 alle 23/07/2024 19:14:33
#durante questo periodo come era la situazione sulla macchina come operating groups o auxiliary groups?

# Occorre creare una colonna sulla tabella status che vada a inserire i dati di operating groups all'interno
#aa73c60c-2ab4-4441-9683-f48197a36686

In [ ]:

# start_date = pd.Timestamp('2024-07-23 00:00:00')
# end_date = pd.Timestamp('2024-07-23 23:59:59')


# df_status_3795 = df_status[
#     (df_status['sdhMachineId'] == 'aa73c60c-2ab4-4441-9683-f48197a36686') &
#     (df_status['from'] >= start_date) &
#     (df_status['from'] <= end_date)
# ]

# print(df_status_3795.to_string(max_cols=df_status_3795.shape[1]))

In [3]:

import pandas as pd
import json
warnings.filterwarnings('ignore')

def filter_and_create_extradata(row, df_op):
    sdhMachineId = str(row['sdhMachineId'])
    start_time = pd.Timestamp(row['from'])
    end_time = pd.Timestamp(row['to'])

    filtered_df_op = df_op[
        (df_op['sdhMachineId'] == sdhMachineId) &
        (
            ((df_op['from_datetime'] <= end_time) & (df_op['from_datetime'] >= start_time)) | 
            ((df_op['to_datetime'] <= end_time) & (df_op['to_datetime'] >= start_time)) |
            ((df_op['from_datetime'] <= start_time) & (df_op['to_datetime'] >= end_time))
        )
    ]
    
    extradata = {}
    
    # Create extradata dictionary from filtered_df_op
    for _, op_row in filtered_df_op.iterrows():
        op_row_from = max(op_row['from_datetime'], start_time)
        op_row_to = min(op_row['to_datetime'], end_time)

        if op_row['correlationKey'] not in extradata:
            extradata[op_row['correlationKey']] = []
        
        extradata[op_row['correlationKey']].append({
            "properties_type": op_row["properties_type"],            
            "data_value": op_row["data_value"],
            "from": op_row_from.isoformat(),  # Convert to ISO format string
            "to": op_row_to.isoformat()       # Convert to ISO format string
        })
    
    return json.dumps(extradata)

df_status = pd.read_csv("./df_Status_.csv")
df_status_op = pd.read_csv("./df_Status_op_.csv")

df_status['from'] = pd.to_datetime(df_status['from'])
df_status['to'] = pd.to_datetime(df_status['to'])
df_status_op['from_datetime'] = pd.to_datetime(df_status_op['from_datetime'])
df_status_op['to_datetime'] = pd.to_datetime(df_status_op['to_datetime'])


# start_date = start_date.tz_localize(None)
# end_date = end_date.tz_localize(None)

if df_status_op['from_datetime'].dt.tz is not None :
    df_status_op['from_datetime'] = df_status_op['from_datetime'].dt.tz_localize(None)
else:
    pass

if df_status_op['to_datetime'].dt.tz is not None:
    df_status_op['to_datetime'] = df_status_op['to_datetime'].dt.tz_localize(None)
else:
    pass

df_status['extradata'] = df_status.apply(lambda row: filter_and_create_extradata(row, df_status_op), axis=1)

df_status["event_ID"] = df_status.index
df_status.set_index('event_ID')


df_status.to_csv("./df_Status_op_f.csv", index=False)

#>180m

C:\Users\dgarattoni\AppData\Local\Temp\ipykernel_12464\1564253734.py:38: DtypeWarning: Columns (2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_status_op = pd.read_csv("./df_Status_op_.csv")

In [1]:
import pandas as pd
import json
import numpy as np
from datetime import datetime
from tqdm import tqdm

def print_with_timestamp(message):
    print(f"{datetime.now().isoformat()} - {message}")

def filter_and_create_extradata(row, filtered_df_op):
    sdhMachineId = str(row['sdhMachineId'])
    start_time = row['from']
    end_time = row['to']

    # Filtra ulteriormente per la macchina specifica
    machine_df_op = filtered_df_op[filtered_df_op['sdhMachineId'] == sdhMachineId]
    
    # Filtra per intervallo di tempo
    mask = (
        ((machine_df_op['from_datetime'] <= end_time) & (machine_df_op['from_datetime'] >= start_time)) | 
        ((machine_df_op['to_datetime'] <= end_time) & (machine_df_op['to_datetime'] >= start_time)) |
        ((machine_df_op['from_datetime'] <= start_time) & (machine_df_op['to_datetime'] >= end_time))
    )
    
    extradata = {}
    
    for _, op_row in machine_df_op[mask].iterrows():
        op_row_from = max(op_row['from_datetime'], start_time)
        op_row_to = min(op_row['to_datetime'], end_time)

        if op_row['correlationKey'] not in extradata:
            extradata[op_row['correlationKey']] = []
        
        extradata[op_row['correlationKey']].append({
            "properties_location": op_row["properties_location"],
            "properties_model": op_row["properties_model"],
            "properties_type": op_row["properties_type"],            
            "data_value": op_row["data_value"],
            "from": op_row_from.isoformat(),
            "to": op_row_to.isoformat()
        })
    
    return json.dumps(extradata)

print_with_timestamp("Loading CSV files...")
df_status = pd.read_csv("./df_Status_.csv")
# Specifica dtype come stringa per le colonne 2 e 3 per evitare il DtypeWarning
df_status_op = pd.read_csv("./df_Status_op_.csv", dtype={2: str, 3: str})

print_with_timestamp("Converting date columns to datetime...")
df_status['from'] = pd.to_datetime(df_status['from'])
df_status['to'] = pd.to_datetime(df_status['to'])
df_status_op['from_datetime'] = pd.to_datetime(df_status_op['from_datetime'])
df_status_op['to_datetime'] = pd.to_datetime(df_status_op['to_datetime'])

print_with_timestamp("Removing timezone from datetime columns if present...")
df_status_op['from_datetime'] = df_status_op['from_datetime'].dt.tz_localize(None)
df_status_op['to_datetime'] = df_status_op['to_datetime'].dt.tz_localize(None)

print_with_timestamp("Filtering df_status_op for relevant date range...")
min_date = df_status['from'].min()
max_date = df_status['to'].max()
filtered_df_op = df_status_op[(df_status_op['from_datetime'] <= max_date) & (df_status_op['to_datetime'] >= min_date)]

print_with_timestamp("Creating extradata for each row in df_status...")
tqdm.pandas()  # Inizializza tqdm con pandas
df_status['extradata'] = df_status.progress_apply(lambda row: filter_and_create_extradata(row, filtered_df_op), axis=1)

print_with_timestamp("Adding event_ID column and setting it as index...")
df_status["event_ID"] = df_status.index
df_status.set_index('event_ID', inplace=True)

output_file = "./df_Status_op_f.csv"
print_with_timestamp(f"Saving the result to {output_file}...")
df_status.to_csv(output_file, index=False)

print_with_timestamp("Process completed successfully.")

2024-07-29T14:44:36.677541 - Loading CSV files...
2024-07-29T14:44:39.137710 - Converting date columns to datetime...
2024-07-29T14:44:47.221533 - Removing timezone from datetime columns if present...
2024-07-29T14:44:47.232533 - Filtering df_status_op for relevant date range...
2024-07-29T14:44:47.324923 - Creating extradata for each row in df_status...

100%|██████████| 1402105/1402105 [20:14:00<00:00, 19.25it/s]

2024-07-30T10:58:47.401934 - Adding event_ID column and setting it as index...
2024-07-30T10:58:47.410935 - Saving the result to ./df_Status_op_f.csv...
2024-07-30T10:58:56.918384 - Process completed successfully.

In [5]:
df_status= df_status.reset_index()

In [6]:
import pandas as pd
import os

file_path21 = r'C:\Users\dgarattoni\OneDrive - scmgroup.com\my ONEDRIVE\Business Analyst in Spare Parts\06.CONTROL ROOM\8. REPORTISTICA\status data\df_Status_op_f.csv'


df_status.to_csv(file_path21, index=False)

print(f"DataFrame saved to {file_path21}")

DataFrame saved to C:\Users\dgarattoni\OneDrive - scmgroup.com\my ONEDRIVE\Business Analyst in Spare Parts\06.CONTROL ROOM\8. REPORTISTICA\status data\df_Status_op_f.csv